// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnLfO4yhuXXTjJ2RLmSCC9ydgWgg2debU',
    appId: '1:442010358792:web:2f07b444a69f3163d4edbd',
    messagingSenderId: '442010358792',
    projectId: 'chat-app-fe46b',
    authDomain: 'chat-app-fe46b.firebaseapp.com',
    storageBucket: 'chat-app-fe46b.appspot.com',
    measurementId: 'G-P4VLVQPECZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsCHpzkYPqMVo8-xWnAUXxnYcNxb7ebYA',
    appId: '1:442010358792:android:2c49d34756d6b28ad4edbd',
    messagingSenderId: '442010358792',
    projectId: 'chat-app-fe46b',
    storageBucket: 'chat-app-fe46b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4IVFAoCsUB-xNMJri0t_CspzT3turBYA',
    appId: '1:442010358792:ios:0511f22fba4cf67fd4edbd',
    messagingSenderId: '442010358792',
    projectId: 'chat-app-fe46b',
    storageBucket: 'chat-app-fe46b.appspot.com',
    iosClientId: '442010358792-ipils66a2lle8e7jg7vmcgg4b1dfdfji.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4IVFAoCsUB-xNMJri0t_CspzT3turBYA',
    appId: '1:442010358792:ios:0511f22fba4cf67fd4edbd',
    messagingSenderId: '442010358792',
    projectId: 'chat-app-fe46b',
    storageBucket: 'chat-app-fe46b.appspot.com',
    iosClientId: '442010358792-ipils66a2lle8e7jg7vmcgg4b1dfdfji.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
